name: Echo password

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo password
        env:
          MY_PASSWORD: ${{ secrets.PASSWORD }}
        run: echo $MY_PASSWORD is my password.
